### ISSUE TITLE
complete example is not complete 

### ISSUE THREAD

**Issue by hilafish1** [cloudposse/terraform-aws-iam-policy#18]
Hi,

You write that the complete example shows a complete usage of that module, but it's not the case. You don't pass conditions.
I tried to pass conditions and I get for each of the values -
```
│     │ condition.value is tuple with 1 element
│
│ This value does not have any attributes.
```

Please add an example of how to pass conditions to the module.

Thanks :)

**Comment by nitrocode** [comment]
Hi @hilafish1 . You're correct, we need to update the docs.

Something like this should work. You'll have to specify the correct `test`, `variable`, and `values` for your statement in a list(map)) form

```hcl
module "iam_policy" {
  source  = "cloudposse/iam-policy/aws"
  # Cloud Posse recommends pinning every module to a specific version
  # version = "x.x.x"

  iam_policy_statements = {
    WriteMyBucket = {
      effect     = "Allow"
      actions    = ["s3:PutObject", "s3:GetObject", "s3:DeleteObject"]
      resources  = ["arn:aws:s3:::test/*"]
      conditions = [
        {
          test     = "",
          variable = "",
          values   = [],
        }
      ]
    },
  }
}
```

https://github.com/cloudposse/terraform-aws-iam-policy/blob/41d2dfaefa3235462797f623fcee33728c9bb892/main.tf#L61-L69

**Comment by hilafish1** [comment]
Thanks :)

I tried passing at as a variable and not directly to the module, like that-

```
variable "policy_conditions" {
  default = [
    {
    test = "StringLike"
    variable = "cloudwatch:namespace"
    values = ["x-*"]
    }
  ]
}
```

and still got that error, any idea why?

and another thing, is when I do pass it as is, it evaluates ok but upon the actual creation, I get -
```
│ Error: while setting policy (), encountered: parsing policy 1: parsing statement 1: 1 error(s) decoding:
│
│ * '[0].Condition' expected a map, got 'slice'
│
```

Full disclosure, I didn't attempt (yet) to use your module as a whole, but to incorporate only the policy document resource since I had a module that did it already and only needed dynamic conditions block, so I might have did something wrong, but I thought it's pretty straight forward.. 
1. copy the data "aws_iam_policy_document" (minus the override/source documents)
2. use it in the aws_iam_policy 

and that's it, but.. nope.
and I understand if it's out of scope of support here :)

**Comment by nitrocode** [comment]
I'm not sure I understand what you're doing with `policy_conditions`. 

Could you include a full reproducible test case ?

**Comment by hilafish1** [comment]
I copied almost all your module locally, to see if it changes anything, and I still get the "slice" error.

how can I upload full code? it doesn't allow me to upload tf files here.
