### ISSUE TITLE
Disable creation of IAM Policy if no iam policy statements

### ISSUE THREAD

**Issue by nitrocode** [cloudposse/terraform-aws-iam-policy#23]
Found a bug? Maybe our [Slack Community](https://slack.cloudposse.com) can help. 

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## Describe the Bug
You may want an IRSA for best practices without an IAM policy to further reduce blast radius so you can have a pod not use the eks node worker role by default.

If you enable an iam role without supplying policy statements, you receive this bug

```hcl
╷
│ Error: creating IAM Policy
|
| MalformedPolicyDocument: Syntax errors in policy.
│ 
│   with module.datadog_agent.module.eks_iam_role.aws_iam_policy.service_account[0],
│   on .terraform/modules/datadog_agent.eks_iam_role/main.tf line 85, in resource "aws_iam_policy" "service_account":
│   85: resource "aws_iam_policy" "service_account" {
```

## Expected Behavior
Enable the IAM role without creating an iam policy resource

## Additional Context
- Similar https://github.com/cloudposse/terraform-aws-helm-release/issues/37

**Comment by Nuru** [comment]
Closing as `wontfix` because the point of this module is to create a policy. If you don't want one created, set `enabled=false`. If you want a policy that does not allow anything, you can pass in 

```hcl
{
    effect = "Deny",
    action = "*",
    resource = "*"
}

```
