### ISSUE TITLE
Versions 0.5.0 and 1.0.0 of this Module have not been Published to the Terraform Registry

### ISSUE THREAD

**Issue by X-Guardian** [cloudposse/terraform-aws-iam-policy#27]
### Describe the Bug

Versions 0.5.0 and 1.0.0 of this Module have not been Published to the Terraform Registry.

Reference: https://registry.terraform.io/modules/cloudposse/iam-policy/aws/latest

### Expected Behavior

The module versions should have been published.

### Steps to Reproduce

N/A

### Screenshots

![image](https://github.com/cloudposse/terraform-aws-iam-policy/assets/32168619/ac0a3b90-b95b-4017-ab01-b8583bdbebd3)

**Comment by Nuru** [comment]
Fixed
